object frmLogin: TfrmLogin
  Left = 0
  Top = 0
  Caption = 'Login'
  ClientHeight = 269
  ClientWidth = 264
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'Segoe UI'
  Font.Style = []
  TextHeight = 15
  object pnlMain: TPanel
    Left = 0
    Top = 113
    Width = 264
    Height = 156
    Align = alClient
    BevelOuter = bvNone
    Padding.Left = 3
    Padding.Top = 3
    Padding.Right = 3
    Padding.Bottom = 3
    TabOrder = 0
    ExplicitTop = 0
    ExplicitWidth = 418
    ExplicitHeight = 441
  end
  object pnlHeader: TPanel
    Left = 0
    Top = 0
    Width = 264
    Height = 113
    Margins.Left = 0
    Margins.Top = 0
    Margins.Right = 0
    Margins.Bottom = 0
    Align = alTop
    BevelOuter = bvNone
    TabOrder = 1
    ExplicitLeft = -5
    ExplicitTop = -3
    object lblEmail: TLabel
      Left = 0
      Top = 63
      Width = 264
      Height = 21
      Align = alBottom
      Caption = 'E-mail'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ExplicitLeft = 16
      ExplicitTop = 35
      ExplicitWidth = 44
    end
    object edtEmail: TEdit
      AlignWithMargins = True
      Left = 3
      Top = 87
      Width = 258
      Height = 23
      Align = alBottom
      TabOrder = 0
      ExplicitLeft = 16
      ExplicitTop = 62
      ExplicitWidth = 362
    end
  end
  object pnlCenter: TPanel
    Left = 0
    Top = 113
    Width = 264
    Height = 156
    Align = alClient
    BevelOuter = bvNone
    Padding.Left = 10
    Padding.Top = 20
    Padding.Right = 10
    Padding.Bottom = 20
    TabOrder = 2
    ExplicitLeft = 120
    ExplicitTop = 176
    ExplicitWidth = 185
    ExplicitHeight = 41
  end
  object pnlCenter2: TPanel
    Left = 0
    Top = 113
    Width = 264
    Height = 156
    Align = alClient
    BevelOuter = bvNone
    TabOrder = 3
    ExplicitLeft = -16
    ExplicitTop = 116
    ExplicitWidth = 441
    ExplicitHeight = 261
    object lblSenha: TLabel
      Left = 0
      Top = 0
      Width = 264
      Height = 21
      Align = alTop
      Caption = 'Senha'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -16
      Font.Name = 'Segoe UI'
      Font.Style = []
      ParentFont = False
      ExplicitLeft = 16
      ExplicitTop = 27
      ExplicitWidth = 43
    end
    object edtsenha: TEdit
      AlignWithMargins = True
      Left = 3
      Top = 24
      Width = 258
      Height = 23
      PasswordChar = '*'
      TabOrder = 0
    end
    object pnlFooter: TPanel
      Left = 0
      Top = 88
      Width = 265
      Height = 73
      BevelOuter = bvNone
      Padding.Left = 10
      Padding.Top = 10
      Padding.Right = 10
      Padding.Bottom = 10
      TabOrder = 1
      object btnEntrar: TButton
        Left = 10
        Top = 10
        Width = 75
        Height = 53
        Align = alLeft
        Caption = 'Entrar'
        TabOrder = 0
        ExplicitLeft = 8
        ExplicitTop = 0
        ExplicitHeight = 105
      end
      object btnCadastrar: TButton
        Left = 180
        Top = 10
        Width = 75
        Height = 53
        Align = alRight
        Caption = 'Cadastrar'
        TabOrder = 1
        ExplicitLeft = 3
        ExplicitTop = 3
        ExplicitHeight = 35
      end
    end
  end
end
